%% Mastermind architecture
graph LR
  subgraph Host
    XCode --- Mastermind
  end
  %%style API fill:#f9f,stroke:#333,stroke-width:4px;
  style Mastermind fill:#fbe983,stroke:#333;
  Mastermind -- HTTP/S --- API
  Device --- XCode
