sequenceDiagram
  participant Device
  participant Test Runner
  participant Mastermind
  participant API

  Test Runner->>Mastermind: http://proxapp:5000/github/start/
  Note right of Mastermind: Mastermind applies github rules from now on
  Mastermind-->>Test Runner: {"driver": "github", "state": "started"}
  Test Runner->>Device: Start test
  Device->>Mastermind: https://api.github.com/...
  Mastermind->>Mastermind: Apply rules
  Mastermind->>API: https://api.github.com/...
  API-->>Mastermind: {...}
  Mastermind->>Mastermind: Apply rules
  Mastermind-->>Device: {...}
  Test Runner->>Mastermind: http://proxapp:5000/stop/
  Note right of Mastermind: Mastermind stops applying rules
  Mastermind-->>Test Runner: {"driver": "github", "state": "stopped"}
  Test Runner->>Device: Start test
  Device->>Mastermind: https://api.github.com/...
  Mastermind->>API: https://api.github.com/...
  API-->>Mastermind: {...}
  Mastermind-->>Device: {...}
